# Generated by Django 5.0.6 on 2024-12-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
