# Generated by Django 5.0.1 on 2025-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_password_enabled',
            field=models.BooleanField(default=True, help_text='Indicates whether the user can log in using email and password.'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email and Password'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', help_text='Specifies how the user registered.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
    ]
